theme: osuny
paginate: 24
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    footer: "/assets/images/logo-white.svg"
  summary:
    position: hero
  search:
    active: true
  design:
    force_full_width: true
  projects:
    index:
      options:
        categories: false
        summary: false
        title: false
        year: false
    single:
      options:
        categories: true
        summary: true
        year: false