theme: osuny
_merge: deep
params:
  plausible: bonnepioche.fr
  logo:
    header: "/assets/images/logo-red.svg"
    footer: "/assets/images/logo-white.svg"
  summary:
    position: hero
  search:
    active: true
    positions:
      - upper-menu
  i18n:
    positions:
      - upper-menu
  breadcrumb:
    position: none
  toc:
    disabled: true
  design:
    force_full_width: true
  persons:
    index:
      taxonomies: false
  projects:
    index:
      options:
        categories: false
        summary: false
        title: false
        year: false
    single:
      options:
        categories: true
        summary: true
        year: false
  share_links:
    enabled: false