theme: osuny
paginate: 24
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    header: "/assets/images/logo-red.svg"
    footer: "/assets/images/logo-white.svg"
  summary:
    position: hero
  search:
    active: true
    positions:
      - upper-menu
  breadcrumb:
    position: none
  toc:
    disabled: true
  menu:
    i18n: 
      display: false
  design:
    force_full_width: true
  persons:
    index:
      taxonomies: true
  projects:
    index:
      options:
        categories: false
        summary: false
        title: false
        year: false
    single:
      options:
        categories: true
        summary: true
        year: false
  share_links:
    enabled: false